---
-
  name: OSPFv2 Process Configuration
  hosts: routers
  gather_facts: no

  tasks:

    - name: Configure OSPFv2, all interfaces in Area-0
      cisco.ios.ios_ospfv2:
        config:
          processes:
          - 
            process_id: 1
            network:
            - address: 0.0.0.0
              area: 0
              wildcard_bits: 255.255.255.255

        state: replaced

    - name: Add OSPFv2 Interface MD5 Authentication
      cisco.ios.ios_command:
        commands: 
        - configure terminal
        - interface range gigabit1 - 6
        - ip ospf authentication message-digest
        - ip ospf message-digest-key 1 md5 0 ine
        - end

    - name: Interface MD5 Authentication Verification
      cisco.ios.ios_command:
        commands: show ip ospf interface | i protocol|Cryptographic
      register: crypto_verify
        
    - debug: var=crypto_verify.stdout_lines

